### ISSUE TITLE
 What should I do after running 'make' 

### ISSUE THREAD

**Issue by uucool** [rchtsang/fie#1]
Hi rchtsang.
After running this step, how can I use FiE to test or reproduce the routine provided by FiE
![图片](https://user-images.githubusercontent.com/100186160/223062901-2535bab2-e1bb-4dbb-9089-b78afb9e50f7.png)

I would appreciate it if I could receive your reply

**Comment by rchtsang** [comment]
sorry, i'm not actually sure. i abandoned my attempts to reproduce the paper quite a while ago, and i don't remember if i was ever able to successfully run fie on test cases. iirc, i was only able to build fie, and i can't remember if the tests were included with the source, but you should be able to just ssh into the vagrant machine and look around and double check.

you can also maybe try contacting the original author (i think his email is on the getting started page i linked in the readme).
